### ISSUE TITLE
Image v3.0 Size Issue

### ISSUE THREAD

**Issue by encient** [gethyas/images#21]
## Description

Thank you for updating to Image v3.0. I have updated my Image to v3.0. My images in the website seems to look weird when the width of the image is more than +-1300px (not sure, just a guess) 

### Steps done

I've updated my repo using this command:
`npm install @hyas/images@latest`

### Actual result

![image](https://github.com/gethyas/images/assets/95013757/e185873d-150d-4e65-8d93-62f8e2679ccd)
The image above became blur with a weird size

![image](https://github.com/gethyas/images/assets/95013757/90be5bef-779e-4c5f-9482-5e70a93b5fd4)
The image above seems to be dragged longer, but I think the width is maintained and not changed, original image shown below:
![image](https://github.com/gethyas/images/assets/95013757/6e8d866f-55ef-4d62-bf91-0e8a37a816b8)

### Environment
```
> encient-blog-hyas@0.0.0 preinfo
> npm version

{
  'encient-blog-hyas': '0.0.0',
  npm: '10.3.0',
  node: '21.5.0',
  acorn: '8.11.2',
  ada: '2.7.4',
  ares: '1.20.1',
  base64: '0.5.1',
  brotli: '1.0.9',
  cjs_module_lexer: '1.2.2',
  cldr: '44.0',
  icu: '74.1',
  llhttp: '9.1.3',
  modules: '120',
  napi: '9',
  nghttp2: '1.58.0',
  nghttp3: '0.7.0',
  ngtcp2: '0.8.1',
  openssl: '3.0.12+quic',
  simdjson: '3.6.2',
  simdutf: '4.0.4',
  tz: '2023c',
  undici: '5.28.2',
  unicode: '15.1',
  uv: '1.47.0',
  uvwasi: '0.0.19',
  v8: '11.8.172.17-node.18',
  zlib: '1.3-22124f5'
}

> encient-blog-hyas@0.0.0 info
> npm list

encient-blog-hyas@0.0.0 D:\encient.github.io
+-- @hyas/doks-core@1.2.0
`-- @hyas/images@3.0.0


> encient-blog-hyas@0.0.0 postinfo
> exec-bin node_modules/.bin/hugo/hugo version
```

**Comment by h-enk** [comment]
Not sure what's with your setup.

- Did you run `npm run clean:build`?
- You could try [updating Doks to v1.3](https://getdoks.org/migration-guides/v-1/v-1-3/)
- Do you have a repo you could share?

It seems to work for me:

![Snag_ffe16ab](https://github.com/gethyas/images/assets/3902872/dc82fbc5-21fa-4451-a0c6-e77e8fe42b18)

**Comment by encient** [comment]
> Not sure what's with your setup.
> 
> * Did you run `npm run clean:build`?
> * You could try [updating Doks to v1.3](https://getdoks.org/migration-guides/v-1/v-1-3/)
> * Do you have a repo you could share?
> 
> It seems to work for me:
> 
> ![Snag_ffe16ab](https://private-user-images.githubusercontent.com/3902872/300170014-dc82fbc5-21fa-4451-a0c6-e77e8fe42b18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MTQyNzgsIm5iZiI6MTcwNjQxMzk3OCwicGF0aCI6Ii8zOTAyODcyLzMwMDE3MDAxNC1kYzgyZmJjNS0yMWZhLTQ0NTEtYTBjNi1lNzdlOGZlNDJiMTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjhUMDM1MjU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2ZiOTZiYTUxZmRiN2NkYzc0NGM1MDMyZTg5MDhmNzllMmNkMjQ3N2FlNTYzZjE4YTlhODYyNDA5YTFlMTBhNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.oNb8WP9PyKJIr4lPi4-bGt8Wuy3iP9h6SeuXV0UN0RM)

I've followed all the steps you mentioned above, and the images have become clearer. However, most of the images are still cropped. You could refer to images in "CTF 2023" `CTF Writeup` and "Build a Linux Profile" in `Blog` [here](https://github.com/encient/encient.github.io) for more information. Thank you!

**Comment by h-enk** [comment]
Update `@hyas/images`:

```bash
npm install @hyas/images@latest
```

[Update parameters](https://images.gethyas.com/docs/start-here/manual-setup/#add-parameters) in `./config/_default/params.toml`:

```toml
# Images (@hyas/images)
[hyas_images]
  [hyas_images.defaults]
    decoding = "async" # sync, async, or auto (default)
    fetchpriority = "auto" # high, low, or auto (default) 
    loading = "lazy" # eager or lazy (default)
    widths = [480, 576, 768, 1025, 1200, 1440] # [640, 768, 1024, 1366, 1600, 1920] for example
    sizes = "75vw" # 100vw (default), 75vw, or auto for example
    process = "" # "fill 1680x720" for example
```

[Add CSS](https://images.gethyas.com/docs/start-here/manual-setup/#add-css) — if not already present

And, boom:

![Snag_19cbe75d](https://github.com/gethyas/images/assets/3902872/5eec0f0d-6963-4366-90ce-02ba6c6a1d71)
